print("Olá!")
print("--------")
print("Podemos ter um enter\ndentro da string.")
print("--------")
print("Podemos ter um tab\ttambém dentro da string.")
print("--------")
print("Aspas simples \' e aspas duplas podem ser escritas também \".")
print("--------")
print("A própria barra invertida também pode ser escapada \\.")
